#!/usr/bin/ruby

require_relative('fusionmanage.rb')

option = ARGV[0]
arg1 = ARGV[1]
arg2 = ARGV[2]

def usage
  puts "Usage: fusionctl <action> <ip address|port> <port>"
end

case option
when "start-network"
  FusionManage.start_network
when "stop-network"
  FusionManage.stop_network
when "restart-network"
  FusionManage.restart_network
when "add-tcp-forward"
  FusionManage.port_forward("add", "tcp", arg1, arg2)
when "delete-tcp-forward"
  FusionManage.port_forward("delete", "tcp", arg1)
when "add-udp-forward"
  FusionManage.port_forward("add", "udp", arg1, arg2)
when "delete-udp-forward"
  FusionManage.port_forward("delete", "udp", arg1)
else
  usage()
  abort()
end
